### ISSUE TITLE
[BUG?] Medical chemicals get processed/metabolized way too quickly

### ISSUE THREAD

**Issue by AGasCanister** [DS-13-Dev-Team/DS13#287]
So, basically.
Currently, medical chemicals get processed very quickly, tricordrazine which should be a slow healing and long lasting chem does the very opposite, it heals quickly and metabolizes fast, same with inaprovaline and dexalin. This happened during the last rounds and I think this should get fixed as chemicals are very important in baychem, specially inaprovaline + dexalin plus combo.

An example, a guy has medium liver damage, you give him 10 units of dylovene, in 10 seconds the dylovene is entirely metabolized and the guy has no more liver damage. (This happened in the second round of the day)

This probably can be fixed by editing the (if there's one) universal rate of chemical metabolizing or manually setting the corret metabolize rate.

**Comment by Snypehunter007** [comment]
Fixed with #332.
