### ISSUE TITLE
[Suggestion] Stairs or an elevator.

### ISSUE THREAD

**Issue by AGasCanister** [DS-13-Dev-Team/DS13#306]
It seems dumb and probably unnecessary, but it's very needed.
Cargo has no way to get craters from the lower deck to the upper deck, and since they have no wrapping paper and no tagger, they can't get them via disposal bin.
Medical has a very hard time to get a dying patient from lower deck to the upper deck.

**Comment by Snypehunter007** [comment]
You're lack of formatting kills me.

But yes, I've been meaning to switch the main hallway ladders to stairs.

**Comment by TheMaskedMan2** [comment]
I suggest more ladders around maint so even if there are stairs it doesn't become a sole chokepoint.

**Comment by AGasCanister** [comment]
> You're lack of formatting kills me.
> 
> But yes, I've been meaning to switch the main hallway ladders to stairs.

I have no idea how to use formatting in github, get me some epic SS13 paperwork system 😏 
also, y o u r *

**Comment by Snypehunter007** [comment]
This'll be added when #315 is merged.
