### ISSUE TITLE
[Suggestion] Make asphyxiation death slower

### ISSUE THREAD

**Issue by AGasCanister** [DS-13-Dev-Team/DS13#360]
Basically what the title says, the tick rate is so elevated that people go brain dead too fast, in a room without pressure, people will go from 100% to 0% of oxygenation in a matter of seconds, to the point where you have no time to react.

I remember clearly in other brainmed based servers where people didn't went brain dead in a matter of 30 seconds while they were flat lined, and same with the non pressurized rooms, you could stay for around a minute without oxygen.

Maybe this could be fixed by lowering the tick rate or editing the values of the brain damage taken by low oxygenation.

**Comment by Snypehunter007** [comment]
Doesn't follow the format.

**Comment by NanakoAC** [comment]
this is definitely not anything to do with tick rate. We're using one life tick per second, and a server fps of 20, like pretty much every other ss13 server. a problem to fix with medical in general

**Comment by AGasCanister** [comment]
Huh, weird then

**Comment by NanakoAC** [comment]
as for how to balance this, we should follow the simple standard of real life. A human should be able to endure three minutes of no oxygen before brain damage starts to happen

falling unconscious much sooner of course

**Comment by NanakoAC** [comment]
tested this today, its not too fast, it can't kill you at all. Dying purely from suffocation is impossible
