### ISSUE TITLE
[SUGGESTION] Map suggestions

### ISSUE THREAD

**Issue by Ketrai** [DS-13-Dev-Team/DS13#407]
#### Description of suggestion
- give bartender and chef a syringe, to let them draw blood for recipes. (special drinks/foods)
- give chef some cuttlefish/lobsters for recipes.
- give chef one box of donuts, to make up for poor grinding making sprinkles hard to get.

**Comment by Snypehunter007** [comment]
Everything but the cuttlefish will be added in #423.
