### ISSUE TITLE
[Suggestion] Prosthetic printer eats too much metal

### ISSUE THREAD

**Issue by AGasCanister** [DS-13-Dev-Team/DS13#417]
Body (for suggestions):
Suggestion:
Currently the prosthetic printer by the surgery suites consume metal like crazy.
For example, you can't print both a left arm and a left hand as you will need extra metal for the left hand.

What do you think it'd add:
I think it will add more time efficiency as you won't need to yell at comms for the local engineer or cargo serviceman to get you metal to medical as you're mid surgery in need of metal to be able to print an organ or prosthetic you need.

**Comment by Snypehunter007** [comment]
We're removing the prosthetic's printer with the next update later today.

Locking.
