### ISSUE TITLE
[BUG] You can put every *TYPE* of liquid into the biomass recycler

### ISSUE THREAD

**Issue by AGasCanister** [DS-13-Dev-Team/DS13#434]
#### Description of issue

What the tytle says, when it means every type of liquid, it means every type of liquid.
Including water, alcohol, blood and more.

#### Difference between expected and actual behavior

You shouldn't be able to put liquids that contain no proteins or nutrients, like water.

#### Steps to reproduce 
1. Get a beaker and a recycler
2. Fill the beaker with water
3. Add water into the recycler and see the biomass tank getting filled

#### Specific information for locating

Biomass recycler, water

#### Length of time in which bug has been known to occur

The lastest test that happened at 16 of June, 2020.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/DS-13-Dev-Team/DS13/issues)

**Comment by NanakoAC** [comment]
Not a bug
The recycling tank doesn't have magical robot arms that prevent you from pouring a beaker in, nor any way to suck only organic liquids from the container.

Things which are not organic do not give biomass. You can pour them in but the liquids are just deleted without granting any biomass at all. I tested your steps, the biomass storage does not start filling

**Comment by Snypehunter007** [comment]
Not a bug.

Locking.
