### ISSUE TITLE
[Suggestion] Add a chemical heater to chemistry

### ISSUE THREAD

**Issue by AGasCanister** [DS-13-Dev-Team/DS13#435]
Body (for suggestions):
Suggestion:
Currently chemistry has no chemical heater, which means chemistry cannot make some advanced chemicals, like Dermalike and Peridaxon, and apparently, RnD can't even make the board for it.

What do you think it'd add:
A chemical heater for advanced chemicals for medical to use.

**Comment by spicyfly** [comment]
Will you settle for a hot plate?

**Comment by Snypehunter007** [comment]
This is a problem with the wiki not displaying the correct requirements for making chemicals.

Locking.
