### ISSUE TITLE
[Suggestion] Add defibs back to medbay

### ISSUE THREAD

**Issue by AGasCanister** [DS-13-Dev-Team/DS13#452]
Suggestion:
Now that the bug that made you unable to interact with buckled / surgically open people is gone, I think we should bring defibs back to medical, why did they even god removed?
Also, since we are going open hub next test I think it will be good to force restart a heart in case of stuff going horribly wrong.
What do you think it'd add:
defibs at medbay for medical usage
Maybe a compact defib for the SMO too?

**Comment by Snypehunter007** [comment]
Despite the horrible formatting, I'll re-add these. Mostly removed them because of the bug described but forgot to re-add them when it was fixed.

**Comment by Snypehunter007** [comment]
Added in #461.

Locking.
