### ISSUE TITLE
[Suggestion] Add a medibot in medbay. (Or the parts to make one)

### ISSUE THREAD

**Issue by AGasCanister** [DS-13-Dev-Team/DS13#489]
Body (for suggestions):
Suggestion:
A Medibot that can help medical
What do you think it'd add:
Currently in those tests we have around 1 medical staff and with some luck 2, if a lot of crew gets injured this can perfectly overwhelm the current doctor, adding a medibot could give him some time to ignore bleeding/burned patients as the medibot will inject tricord to those that don't need immediate attention or if the doctor is busy doing surgery

Or at least the parts to made one, like a robotic arm, since there's currently no way to get it.

**Comment by NanakoAC** [comment]
I don't see any issues with medibots as a concept. But i have an objection to this specific proposal.

The construction of a bot should be something for either engineering or science to do, and it ought to be constructed, not simply given.

**Comment by Snypehunter007** [comment]
I'm going to deny this one, as medibots don't really fit in the Dead Space universe.
