### ISSUE TITLE
[BUG] Humans that have no arms cannot be interacted with.

### ISSUE THREAD

**Issue by AGasCanister** [DS-13-Dev-Team/DS13#626]
#### Description of issue:

If a guy has both of his arms missing other people won't be able to interact with him. Help and grab intent do not work, you cannot also shake him.

#### Difference between expected and actual behavior:

You should be able to interact with him even if he has both missing arms

#### Steps to reproduce:
1. Get a human
2. Get both of his arms removed (No stumps)
3. Try to interact with him via help or grab intent.

**Comment by AGasCanister** [comment]
update: this happens if a guy has at least 1 (one) missing limb

**Comment by DTraitor** [comment]
Couldn't reproduce it with 1 missing limb but it still happens if person has no hands. The game says: "You can't use your hand."
You can still attach a new limb
