### ISSUE TITLE
[BUG] Throwing a person to another person deals dangerously insane ammount of damage

### ISSUE THREAD

**Issue by AGasCanister** [DS-13-Dev-Team/DS13#641]
#### Description of issue:

Literally you can instantly kill a guy with this method by simple throwing a guy to another guy, you can from blowing up their arm to cut them in half.

#### Difference between expected and actual behavior:

You shouldn't be able to cut a person in half by throwing another person at them

#### Steps to reproduce:
1. Get 2 humans. Human A and Human B.
2. Grab intent Human A then reinforce the grab to aggressive
3. Throw Human A to Human B.

**Comment by NanakoAC** [comment]
Fixed an issue yesterday that was causing thrown objects to deal damage twice, lets see how that goes before giving this another look
