### ISSUE TITLE
[BUG] The NutriCubes by the BioLab have lost their sprite.

### ISSUE THREAD

**Issue by AGasCanister** [DS-13-Dev-Team/DS13#642]
#### Description of issue:

The nutri cubes that the biolab has by the top right corner by the table have lost their sprite and appear invisible without sprite, currently the only way to get the cubes is by alt clicking them.

#### Difference between expected and actual behavior:

They should have sprites so we can click them

#### Steps to reproduce:
1. Get to BioLab
2. Search for the nutri cubes
3. ???
![image](https://user-images.githubusercontent.com/55928412/89791057-10c67000-db23-11ea-9fca-f49cb9a98c01.png)

**Comment by JakeDaBoss** [comment]
This was likely caused by an update I did, somehow, as I changed their sprites.

I'll fix this shortly.
