### ISSUE TITLE
[BUG] Failing on removing shrapnel from the head will decap the patient

### ISSUE THREAD

**Issue by AGasCanister** [DS-13-Dev-Team/DS13#649]
#### Description of issue:

If you have a patient that has shrapnel in his head, the idea is to remove it, but after opening his head failing on the shrapnel removal hemostat step will cause him to be decapitated, killing him instantly.

#### Difference between expected and actual behavior:

The idea is that he shouldn't get decapitated by failing at removing shrapnel

#### Steps to reproduce:
1. Get a guy with shrapnel on his head
2. Open his head (Scalpel, hemostat, retractor)
3. Get on the shrapnel removal part and fail on purpose

(I am not sure if this happens with other surgical steps but apparently surgery fails do a lot of damage)

**Comment by NanakoAC** [comment]
more of a balance issue than a bug, but yea this sounds a bit too powerful. Its a good idea to heal superficial damage before attempting surgery though

**Comment by AGasCanister** [comment]
Oof true, but apparently shrapnel gives some permanent damage that you cannot heal

**Comment by NanakoAC** [comment]
now fixed
