### ISSUE TITLE
[Suggestion] When a human goes brain dead, turn off part of his equipment to reduce lag.

### ISSUE THREAD

**Issue by AGasCanister** [DS-13-Dev-Team/DS13#650]
#### Suggestion:
In order to reduce lag I thought of doing something that CM makes to help remove some load.
When a human goes brain dead, part of his equipment could be turned off automatically (like huds, internals) in order to improve the performance with a lore excuse of being connected to the RIG.

#### What do you think it'd add:
Less lag in the future of big pops

**Comment by NanakoAC** [comment]
most of it already is, vision devices whether in a rig or not, don't update in clientless mobs. Rigs might still be doing some processing though, i'll look into optimising that

**Comment by Snypehunter007** [comment]
Most of the lag has been cleared up for the most part without disabling equipment on death.

Closing.
