### ISSUE TITLE
[BUG] Lurkers only have 1 limb (chest)

### ISSUE THREAD

**Issue by AGasCanister** [DS-13-Dev-Team/DS13#651]
#### Description of issue:

Title, Lurkers the white dogs with tentacles apparently have only one limb and are very hard to kill

#### Difference between expected and actual behavior:

They should probably have more limbs like other necros instead of the chest

**Comment by aguyiguess** [comment]
I've seen their tentacles get shot off

**Comment by NanakoAC** [comment]
Lurkers have three limbs. 
Left Tentacle, bound to Left Arm
Middle Tentacle, bound to Head
right Tentacle, bound to right arm

target the appropriate parts to cut them off, they die if all three are lost
