### ISSUE TITLE
[Suggestion] Nerf alcohol damage

### ISSUE THREAD

**Issue by AGasCanister** [DS-13-Dev-Team/DS13#655]
#### Suggestion:
Currently, drinking an entire alcohol bottle will pretty much kill you and you cannot stop it unless medical is somewhat competent, literally an entire bottle will kill your liver leading this to kidney failure and then complete organ failure, killing you in less than 5 minutes.
I thought about nerfing how much alcohol damages the liver to some acceptable levels so it doesn't kill your liver with one bottle in such low time.

#### What do you think it'd add:
Less death by alcohol

**Comment by AshTheGuy** [comment]
just dont drink Alcohol

**Comment by Snypehunter007** [comment]
@AGasCanister What bottle did you drink?

**Comment by AGasCanister** [comment]
@Snypehunter007 wasn't me, but at least I can confirm that a bottle of vodka does that

**Comment by NanakoAC** [comment]
Alcohol is definitely broken and dumb. And I'll definitely be overhauling it around the time of psychosis, since getting drunk is a good way to forget some of the horrors you've seen

Maybe sooner, we'll see

**Comment by AshTheGuy** [comment]
> Alcohol is definitely broken and dumb. And I'll definitely be overhauling it around the time of psychosis, since getting drunk is a good way to forget some of the horrors you've seen
> 
> Maybe sooner, we'll see

That Eris feature should be added, so Hyperzine should give you a mood boost ;)
