### ISSUE TITLE
[BUG] Some tools don't show their tool properties when you examine them

### ISSUE THREAD

**Issue by AGasCanister** [DS-13-Dev-Team/DS13#671]
#### Description of issue:

Currently there are some tool variants that can be used in the construction of diverse stuff, but we don't always know if a tool can do X thing, when we examine tools we cannot see their tool value.

#### Difference between expected and actual behavior:

As Nanako said, we should be able to see the tool value and what they can do and how good they can do it.

#### Steps to reproduce:
1. Get a tool
2. Examine it

Examples
![image](https://user-images.githubusercontent.com/55928412/90342114-00703280-e006-11ea-9618-d45297abf4a1.png)
![image](https://user-images.githubusercontent.com/55928412/90342132-1e3d9780-e006-11ea-999e-2ef082600353.png)

**Comment by aguyiguess** [comment]
I looked into this and it seems like it isn't a bug. It only displays those values if they have been changed, and for the big wrench, neither the precision nor work speed have been modified.
