### ISSUE TITLE
[Oversight] CSCIO doesn't spawn with medical channel

### ISSUE THREAD

**Issue by AGasCanister** [DS-13-Dev-Team/DS13#678]
#### Description of issue:

Unlike RAs, the CSCIO doesn't start with a medical channel, forcing him to get one via the medical equipment lockers.

#### Difference between expected and actual behavior:

If RAs have medical channel access, the CSCIO should also have it.

#### Steps to reproduce:
1A. be CSCIO, no medical channel
1B. Be RA, you got medical channel

**Comment by Snypehunter007** [comment]
Huh, it should. I look at this.

**Comment by JakeDaBoss** [comment]
@Snypehunter007 fixed.
