### ISSUE TITLE
[Suggestion] Add 2 surgeon equipment lockers in medical equipment room

### ISSUE THREAD

**Issue by AGasCanister** [DS-13-Dev-Team/DS13#679]
#### Suggestion:

Currently, medical equipment room lacks two surgeon lockers which might be useful for the two surgeons that take part in the rounds, I thought of expanding the room a bit or replacing 2 MD lockers with SRG lockers. There could also be a SRG locker in each OR room.

#### What do you think it'd add:

More clothing options for SRGs and the equipment they might need from the lockers.

**Comment by Snypehunter007** [comment]
I'll put them in the surgical suites for now. It isn't a perfect solution but until some more space is added, it'll do.
